export const GET_TODO_DATA = 'GET_TODO_DATA';
export const GET_TODO_DATA_SUCCESS = 'GET_TODO_DATA_SUCCESS';
export const GET_TODO_DATA_FAILURE = 'GET_TODO_DATA_FAILURE';


export const ADD_TODO_DATA = 'ADD_TODO_DATA';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';